<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\src\Novolis.MSBuild.LibraryReference\build\Novolis.MSBuild.LibraryReference.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <LibraryReference Include="Newtonsoft.Json"
                      Version="13.0.3"
                      ProjectPath="$(MSBuildThisFileDirectory)missing\Nope.csproj" />
  </ItemGroup>

  <Import Project="..\..\..\src\Novolis.MSBuild.LibraryReference\build\Novolis.MSBuild.LibraryReference.targets" />
</Project>
